<a href="https://colab.research.google.com/github/sethukrish6420/sethu/blob/main/class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [4]:
np.array??

In [5]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.array([2,3])

array([2, 3])

In [10]:
np.array([[[2,3],[3,4],[7,6]]])

array([[[2, 3],
        [3, 4],
        [7, 6]]])

In [11]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.exp(np.ones((3,3)))

array([[2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183]])

In [23]:
def sigmoid(x):
  return(1/(1+np.exp(-x)))
sigmoid(np.ones((3,3)))

array([[0.73105858, 0.73105858, 0.73105858],
       [0.73105858, 0.73105858, 0.73105858],
       [0.73105858, 0.73105858, 0.73105858]])